---
- hosts: Syndicate
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: Perform a dist-upgrade
      apt:
        upgrade: dist

    - name: Remove unused packages
      apt:
        autoremove: yes

    - name: Clean up downloaded archives
      apt:
        autoclean: yes
