---
- name: System update, upgrade, and Flatpak maintenance
  hosts: Titanas
  become: yes

  vars:
    flatpak_installed: true

  tasks:

    - name: Update all Flatpak apps
      ansible.builtin.command:
        cmd: flatpak update -y
      when: flatpak_installed

    - name: Remove unused Flatpak apps
      ansible.builtin.command:
        cmd: flatpak uninstall --unused --delete-data -y
      environment:
        DISPLAY: ":0"
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
      register: flatpak_cleanup_result
