version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /home/funmicra/Appdata/vaultwarden/data/:/data/
    ports:
      - 89:80
    environment:
      - DOMAIN=Domain
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=Extrude-Striving-Enjoyment1-Comprised-Bounding-Monopoly-Stammer-Suave-Ditch-Rounding
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=tue
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=5
#      - SIGNUPS_DOMAINS_WHITELIST=yourdomainhere.com,anotherdomain.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=from_email
      - SMTP_FROM_NAME=name
      - SMTP_SECURITY=force_tls
      - SMTP_PORT=465
      - SMTP_USERNAME=user@mail.com
      - SMTP_PASSWORD=password
      - SMTP_AUTH_MECHANISM="Mechanism"

networks:
  default:
    external:
      name: Apps-Network
