---
version: "2.1"
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /home/funmicra/Appdata/libreoffice/config:/config
    ports:
      - 3010:3000
      - 3011:3001
    restart: unless-stopped

networks:
  default:
    external:
      name: Apps-Network
