version: '3'  # Docker Compose file version

services:
  # Nextcloud service configuration
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000               # Process User ID
      - PGID=1000               # Process Group ID
      - TZ=Europe/Athens        # Timezone
    volumes:
      - nextcloud_config:/config     # Nextcloud configuration data
      - nextcloud_data:/data         # Nextcloud data
      - /media/storage:/media/storage   # Mount from host system
      - /media/NFS-WD:/media/NFS-WD     # Another mount from host system
    ports:
      - 443:443              # Maps host port 443 to container port 443 for HTTPS
    depends_on:
      - mariadb              # Depends on the MariaDB service
    restart: unless-stopped  # Restart policy

  # MariaDB service configuration
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextcloud_db
    environment:
      - PUID=1000               # Process User ID
      - PGID=1000               # Process Group ID
      - TZ=Europe/Athens        # Timezone
      - MYSQL_ROOT_PASSWORD="ROOT_ACCESS_PASSWORD"   # MariaDB root password
      - MYSQL_DATABASE="USER_DB_NAME"                # Database name
      - MYSQL_USER="MYSQL_USER"                      # Database user
      - MYSQL_PASSWORD="DATABASE_PASSWORD"           # Database password
    volumes:
      - nextcloud_db_config:/config    # MariaDB configuration data
      - nextcloud_db_data:/data        # MariaDB data
    ports:
      - 3306:3306             # Maps host port 3306 to container port 3306 for MySQL
    restart: unless-stopped   # Restart policy

  # Collabora Online service configuration
  code:
    image: collabora/code:latest  # Docker image to use for the service
    container_name: collabora-office  # Name of the container
    restart: always  # Restart policy: always (restart container automatically)
    environment:
      - password=${COLLABORA_PASSWORD}  # Set environment variable for password
      - username=${COLLABORA_USERNAME}  # Set environment variable for username
      - domain=${COLLABORA_DOMAIN}      # Set environment variable for domain
      - extra_params=--o:ssl.enable=true  # Additional parameters for collabora
    ports:
      - 9980:9980  # Map host port 9980 to container port 9980 for access

networks:
  default:
    external:
      name: Apps-Network  # External network configuration named Apps-Network

volumes:
  nextcloud_config:
    name: nextcloud_config   # Named volume for Nextcloud config
    external: true           # External volume
  nextcloud_data:
    name: nextcloud_data     # Named volume for Nextcloud data
    external: true           # External volume
  nextcloud_db_config:
    name: nextcloud_db_config   # Named volume for MariaDB config
    external: true               # External volume
  nextcloud_db_data:
    name: nextcloud_db_data     # Named volume for MariaDB data
    external: true               # External volume
