version: "3"

services:
  watchtower:
    image: containrrr/watchtower  # Use the Watchtower Docker image
    container_name: watchtower  # Set the name of the container to "watchtower"
    restart: unless-stopped  # Restart the container unless stopped manually

    # Environment variables for Watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=21600  # Set the polling interval to 6 hours (21600 seconds)
      - TZ=Europe/Athens
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for container to access host's Docker daemon

networks:
  default:
    external:
      name: Apps-Network  # Use an external network named "Apps-Network"
