version: "2.1"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN  # Add NET_ADMIN capability
      - SYS_MODULE  # Optional: Add SYS_MODULE capability
    environment:
      - PUID=${PUID}  # User ID for file permissions
      - PGID=${PGID}  # Group ID for file permissions
      - TZ=${TZ}  # Timezone
      - SERVERURL=${SERVERURL}  # Optional: Server URL
      - SERVERPORT=${SERVERPORT}  # Optional: Server port
      - PEERS=${PEERS}  # Optional: Peer configuration
      - PEERDNS=${PEERDNS}  # Optional: Peer DNS configuration
      - INTERNAL_SUBNET=${INTERNAL_SUBNET}  # Optional: Internal subnet
      - ALLOWEDIPS=${ALLOWEDIPS}  # Optional: Allowed IPs
      - PERSISTENTKEEPALIVE_PEERS=${PERSISTENTKEEPALIVE_PEERS}  # Optional: Persistent keepalive peers
      - LOG_CONFS=${LOG_CONFS}  # Optional: Log configurations
    volumes:
      - wireguard_data:/config  # Mount external volume for WireGuard configuration
      - /lib/modules:/lib/modules  # Optional: Mount kernel modules
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}/udp  # Expose and forward port using UDP
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1  # Set a specific kernel parameter
    restart: unless-stopped  # Restart policy for the container

volumes:
  wireguard_data:
    external: true  # Define an external volume named 'wireguard_data'

networks:
  default:
    external:
      name: Apps-Network  # External network named 'Apps-Network'
