version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/funmicra/Appdata/Nginx-Proxy/data:/data
      - /home/funmicra/Appdata/Nginx-Proxy/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

networks:
  default:
    external:
      name: Apps-Network
