version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /home/funmicra/Appdata/metube:/downloads

networks:
  default:
    external:
      name: Apps-Network
