name: Rebuild Home Lab

on:
  push:
    branches: [main]
  workflow_dispatch:  # manual trigger

jobs:
  lint:
    name: Lint Ansible Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint

      - name: Run ansible-lint
        run: ansible-lint ansible/site.yml

      - name: Run yamllint
        run: yamllint ansible/

  deploy:
    name: Rebuild Lab (Ansible Playbook)
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run on main
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: pip install ansible

      - name: Decrypt Ansible Vault (if applicable)
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          ansible-playbook -i ansible/inventory/hosts ansible/site.yml --vault-password-file vault_pass.txt

