---
- hosts: test
  user: root
  tasks:
  - name: Create users "ansible" on remote hosts
    ansible.builtin.user:
      name: ansible
      password: H84zzoMc
      append: yes
      groups: sudo
      shell: /bin/bash
      state: present
 
