---
- name: System update, upgrade, and Flatpak maintenance
  hosts: Titanas
  become: yes

  vars:
    flatpak_installed: false

  tasks:

    - name: Update all Flatpak apps
      ansible.builtin.command:
        cmd: flatpak update -y
      when: flatpak_installed

    - name: Remove unused Flatpak apps
      ansible.builtin.command:
        cmd: flatpak uninstall --unused --delete-data -y
      when: flatpak_installed
