---
- hosts: test
  user: ansible
  become: yes
  tasks:
  - name: lock user "root"
    ansible.builtin.user:
      name: root
      state: present
      password_lock: yes
      shell: /sbin/nologin 
