---
- name: Manage Snap packages on Debian/Ubuntu
  hosts: Titanas
  become: yes

  tasks:

    - name: Ensure Snap is installed
      ansible.builtin.package:
        name: snapd
        state: present
      register: snapd_installed

    - name: Ensure Snap is active and running
      ansible.builtin.systemd:
        name: snapd
        state: started
        enabled: true
      when: snapd_installed is changed

    - name: Update APT package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all APT packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes

    - name: Refresh Snap packages
      ansible.builtin.command: snap refresh
      register: snap_refresh
      changed_when: "'All snaps up to date' not in snap_refresh.stdout"

    - name: Get list of disabled Snap packages
      ansible.builtin.command: snap list --all | awk '/disabled/{print $1, $3}'
      register: disabled_snaps
      changed_when: false

    - name: Remove disabled Snap packages
      ansible.builtin.command:
        cmd: "snap remove --purge {{ item }}"
      loop: "{{ disabled_snaps.stdout_lines }}"
      when: disabled_snaps.stdout != ""
      ignore_errors: true
